
-- Début de la transaction
BEGIN;

-- Toujours utiliser le même schéma
SET search_path TO parcourStat_schema;


CREATE TABLE TMP_parcoursup2018 AS (
SELECT
    	CAST("Session" as INT) as "Session",
	TRIM("Code_UAI_etablissement") as "Code_uai_etablissement",
	TRIM("Etablissement") as "Etablissement",
	CAST("Code_departemental_etablissement" as INT) as "Code_departemental_etablissement",
	TRIM("Departement_etablissement") as "Departement_etablissement",
	TRIM("Region_etablissement") as "Region_etablissement",
	TRIM("Academie_etablissement") as "Academie_etablissement",
	TRIM("Filiere_formation_tres_agregee") as "Filiere_formation_tres_agregee",
	TRIM("Filiere_formation") as "Filiere_formation",
	TRIM("Concours_communs_et_banques_epreuves") as "Concours_communs_et_banques_epreuves",
	TRIM("Filiere_formation_detaillee") as "Filiere_formation_detaillee",
	TRIM("Filiere_formation_tres_detaillee") as "Filiere_formation_tres_detaillee",
	TRIM("Lien_formation_plateforme_Parcoursup") as "Lien_formation_plateforme_parcoursup",
	TRIM("Coordonnees_GPS_formation") as "Coordonnees_gps_formation",
	CAST("Capacite_etablissement_par_formation" as INT) as "Capacite_etablissement_par_formation",
	CAST("1_Effectif_total_candidats_pour_formation" as INT) as "1_effectif_total_candidats_pour_formation",
	CAST("1_1_Dont_effectif_candidates_pour_formation" as INT) as "1_1_dont_effectif_candidates_pour_formation",
	CAST("2_Effectif_total_candidats_phase_principale" as INT) as "2_effectif_total_candidats_phase_principale",
	CAST("2_1_Dont_effectif_candidats_postule_internat" as INT) as "2_1_dont_effectif_candidats_postule_internat",
	CAST("3_Effectif_candidats_neo_bacheliers_generaux_phase_principale" as INT) as "3_effectif_candidats_neo_bacheliers_generaux_phase_principale",
	CAST("3_1_Dont_effectif_candidats_boursiers_neo_bacheliers_generaux_phase_principale" as INT) as "3_1_dont_effectif_candidats_boursiers_neo_bacheliers_generaux_phase_principale",
	CAST("4_Effectif_candidats_neo_bacheliers_technologiques_phase_principale" as INT) as "4_effectif_candidats_neo_bacheliers_technologiques_phase_principale",
	CAST("4_1_Dont_effectif_candidats_boursiers_neo_bacheliers_technologiques_phase_principale" as INT) as "4_1_dont_effectif_candidats_boursiers_neo_bacheliers_technologiques_phase_principale",
	CAST("5_Effectif_candidats_neo_bacheliers_professionnels_phase_principale" as INT) as "5_effectif_candidats_neo_bacheliers_professionnels_phase_principale",
	CAST("5_1_Dont_effectif_candidats_boursiers_neo_bacheliers_professionnels_phase_principale" as INT) as "5_1_dont_effectif_candidats_boursiers_neo_bacheliers_professionnels_phase_principale",
	CAST("6_Effectif_autres_candidats_phase_principale" as INT) as "6_effectif_autres_candidats_phase_principale",
	CAST("7_Effectif_total_candidats_phase_complementaire" as INT) as "7_effectif_total_candidats_phase_complementaire",
	CAST("8_Effectif_candidats_neo_bacheliers_generaux_phase_complementaire" as INT) as "8_effectif_candidats_neo_bacheliers_generaux_phase_complementaire",
	CAST("9_Effectif_candidats_neo_bacheliers_technologique_phase_complementaire" as INT) as "9_effectif_candidats_neo_bacheliers_technologique_phase_complementaire",
	CAST("10_Effectif_candidats_neo_bacheliers_professionnels_phase_complementaire" as INT) as "10_effectif_candidats_neo_bacheliers_professionnels_phase_complementaire",
	CAST("11_Effectifs_autres_candidats_phase_complementaire" as INT) as "11_effectifs_autres_candidats_phase_complementaire",
	CAST("12_Effectif_total_candidats_classes_par_etablissement_phase_principale" as INT) as "12_effectif_total_candidats_classes_par_etablissement_phase_principale",
	CAST("13_Effectif_candidats_classes_par_etablissement_phase_complementaire" as INT) as "13_effectif_candidats_classes_par_etablissement_phase_complementaire",
	CAST("14_Effectif_candidats_classes_par_etablissement_internat_CPGE" as INT) as "14_effectif_candidats_classes_par_etablissement_internat_cpge",
	CAST("15_Effectif_candidats_classes_par_etablissement_hors_internat_CPGE" as INT) as "15_effectif_candidats_classes_par_etablissement_hors_internat_cpge",
	CAST("16_Effectif_candidats_neo_bacheliers_generaux_classes_par_etablissement" as INT) as "16_effectif_candidats_neo_bacheliers_generaux_classes_par_etablissement",
	CAST("16_1_Dont_effectif_candidats_boursiers_neo_bacheliers_generaux_classes_par_etablissement" as INT) as "16_1_dont_effectif_candidats_boursiers_neo_bacheliers_generaux_classes_par_etablissement",
	CAST("17_Effectif_candidats_neo_bacheliers_technologiques_classes_par_etablissement" as INT) as "17_effectif_candidats_neo_bacheliers_technologiques_classes_par_etablissement",
	CAST("17_1_Dont_effectif_candidats_boursiers_neo_bacheliers_technologiques_classes_par_etablissement" as INT) as "17_1_dont_effectif_candidats_boursiers_neo_bacheliers_technologiques_classes_par_etablissement",
	CAST("18_Effectif_candidats_neo_bacheliers_professionnels_classes_par_etablissement" as INT) as "18_effectif_candidats_neo_bacheliers_professionnels_classes_par_etablissement",
	CAST("18_1_Dont_effectif_candidats_boursiers_neo_bacheliers_professionnels_classes_par_etablissement" as INT) as "18_1_dont_effectif_candidats_boursiers_neo_bacheliers_professionnels_classes_par_etablissement",
	CAST("19_Effectif_autres_candidats_classes_par_etablissement" as INT) as "19_effectif_autres_candidats_classes_par_etablissement",
	CAST("20_Effectif_total_candidats_recu_proposition_admission_part_etablissement" as INT) as "20_effectif_total_candidats_recu_proposition_admission_part_etablissement",
	CAST("Rang_dernier_appele" as INT) as "Rang_dernier_appele",
	CAST("21_Effectif_total_candidats_accepte_proposition_etablissement_admis" as INT) as "21_effectif_total_candidats_accepte_proposition_etablissement_admis",
	CAST("21_1_Dont_effectif_candidates_admises" as INT) as "21_1_dont_effectif_candidates_admises",
	CAST("22_Effectif_admis_phase_principale" as INT) as "22_effectif_admis_phase_principale",
	CAST("23_Effectif_admis_phase_complementaire" as INT) as "23_effectif_admis_phase_complementaire",
	CAST("23_1_Dont_effectif_admis_internat" as INT) as "23_1_dont_effectif_admis_internat",
	CAST("23_2_Dont_effectif_admis_boursiers_neo_bacheliers" as INT) as "23_2_dont_effectif_admis_boursiers_neo_bacheliers",
	CAST("24_Effectif_admis_neo_bacheliers" as INT) as "24_effectif_admis_neo_bacheliers",
	CAST("25_Effectif_admis_neo_bacheliers_generaux" as INT) as "25_effectif_admis_neo_bacheliers_generaux",
	CAST("26_Effectif_admis_neo_bacheliers_technologiques" as INT) as "26_effectif_admis_neo_bacheliers_technologiques",
	CAST("27_Effectif_admis_neo_bacheliers_professionnels" as INT) as "27_effectif_admis_neo_bacheliers_professionnels",
	CAST("28_Effectif_autres_candidats_admis" as INT) as "28_effectif_autres_candidats_admis",
	CAST("28_1_Dont_effectif_admis_neo_bacheliers_sans_information_mention" as INT) as "28_1_dont_effectif_admis_neo_bacheliers_sans_information_mention",
	CAST("28_2_Dont_effectif_admis_neo_bacheliers_sans_mention" as INT) as "28_2_dont_effectif_admis_neo_bacheliers_sans_mention",
	CAST("28_3_Dont_effectif_admis_neo_bacheliers_mention_Assez_Bien" as INT) as "28_3_dont_effectif_admis_neo_bacheliers_mention_assez_bien",
	CAST("28_4_Dont_effectif_admis_neo_bacheliers_mention_Bien" as INT) as "28_4_dont_effectif_admis_neo_bacheliers_mention_bien",
	CAST("28_5_Dont_effectif_admis_neo_bacheliers_mention_Tres_Bien" as INT) as "28_5_dont_effectif_admis_neo_bacheliers_mention_tres_bien",
	CAST("29_Effectif_admis_neo_bacheliers_generaux_mention" as INT) as "29_effectif_admis_neo_bacheliers_generaux_mention",
	CAST("30_Effectif_admis_neo_bacheliers_technologiques_mention" as INT) as "30_effectif_admis_neo_bacheliers_technologiques_mention",
	CAST("31_Effectif_admis_neo_bacheliers_professionnels_mention" as INT) as "31_effectif_admis_neo_bacheliers_professionnels_mention",
	CAST("31_1_Dont_effectif_admis_issus_meme_etablissement_BTS_CPGE" as INT) as "31_1_dont_effectif_admis_issus_meme_etablissement_bts_cpge",
	CAST("31_2_Dont_effectif_admises_issues_meme_etablissement_BTS_CPGE" as INT) as "31_2_dont_effectif_admises_issues_meme_etablissement_bts_cpge",
	CAST("31_3_Dont_effectif_admis_issus_meme_academie" as INT) as "31_3_dont_effectif_admis_issus_meme_academie",
	CAST("31_4_Dont_effectif_admis_issus_meme_academie_Paris_Creteil_Versailles_reunies" as INT) as "31_4_dont_effectif_admis_issus_meme_academie_paris_creteil_versailles_reunies",
	CAST("pourcentage_admis_dont_filles" as INT) as "Pourcentage_admis_dont_filles",
	CAST("pourcentage_admis_neo_bacheliers_issus_meme_academie" as INT) as "Pourcentage_admis_neo_bacheliers_issus_meme_academie",
	CAST("pourcentage_admis_neo_bacheliers_issus_meme_academie_Paris_Creteil_Versailles_reunies" as INT) as "Pourcentage_admis_neo_bacheliers_issus_meme_academie_paris_creteil_versailles_reunies",
	CAST("pourcentage_admis_neo_bacheliers_issus_meme_etablissement_BTS_CPGE" as INT) as "Pourcentage_admis_neo_bacheliers_issus_meme_etablissement_bts_cpge",
	CAST("pourcentage_admis_neo_bacheliers_boursiers" as INT) as "Pourcentage_admis_neo_bacheliers_boursiers",
	CAST("pourcentage_admis_neo_bacheliers" as INT) as "Pourcentage_admis_neo_bacheliers",
	CAST("pourcentage_admis_neo_bacheliers_sans_information_mention" as INT) as "Pourcentage_admis_neo_bacheliers_sans_information_mention",
	CAST("pourcentage_admis_neo_bacheliers_sans_mention" as INT) as "Pourcentage_admis_neo_bacheliers_sans_mention",
	CAST("pourcentage_admis_neo_bacheliers_mention_Assez_Bien" as INT) as "Pourcentage_admis_neo_bacheliers_mention_assez_bien",
	CAST("pourcentage_admis_neo_bacheliers_mention_Bien" as INT) as "Pourcentage_admis_neo_bacheliers_mention_bien",
	CAST("pourcentage_admis_neo_bacheliers_mention_Tres_Bien" as INT) as "Pourcentage_admis_neo_bacheliers_mention_tres_bien",
	CAST("pourcentage_admis_neo_bacheliers_generaux" as INT) as "Pourcentage_admis_neo_bacheliers_generaux",
	CAST("31_5_Dont_pourcentage_admis_mention" as INT) as "31_5_dont_pourcentage_admis_mention",
	CAST("pourcentage_admis_neo_bacheliers_technologiques" as INT) as "Pourcentage_admis_neo_bacheliers_technologiques",
	CAST("31_6_Dont_pourcentage_admis_mention_1" as INT) as "31_6_dont_pourcentage_admis_mention_1",
	CAST("pourcentage_admis_neo_bacheliers_professionnels" as INT) as "Pourcentage_admis_neo_bacheliers_professionnels",
	CAST("31_7_Dont_pourcentage_admis_mention_2" as INT) as "31_7_dont_pourcentage_admis_mention_2",
	TRIM("tri") as "Tri"
FROM
    "Test".parcoursup2018
);


CREATE TABLE TMP_parcoursup2024 AS (
SELECT
    	CAST("Session" as INT) as "Session",
	TRIM("Statut_etablissement_filiere_formation_public_prive") as "Statut_etablissement_filiere_formation_public_prive",
	TRIM("Code_UAI_etablissement") as "Code_uai_etablissement",
	TRIM("Etablissement") as "Etablissement",
	CAST("Code_departemental_etablissement" as INT) as "Code_departemental_etablissement",
	TRIM("Departement_etablissement") as "Departement_etablissement",
	TRIM("Region_etablissement") as "Region_etablissement",
	TRIM("Academie_etablissement") as "Academie_etablissement",
	TRIM("Commune_etablissement") as "Commune_etablissement",
	TRIM("Filiere_formation") as "Filiere_formation",
	TRIM("Selectivite") as "Selectivite",
	TRIM("Filiere_formation_tres_agregee") as "Filiere_formation_tres_agregee",
	TRIM("Filiere_formation_detaillee") as "Filiere_formation_detaillee",
	TRIM("Filiere_formation_1") as "Filiere_formation_1",
	TRIM("Filiere_formation_detaillee_bis") as "Filiere_formation_detaillee_bis",
	TRIM("Filiere_formation_tres_detaillee") as "Filiere_formation_tres_detaillee",
	TRIM("Coordonnees_GPS_formation") as "Coordonnees_gps_formation",
	CAST("Capacite_etablissement_par_formation" as INT) as "Capacite_etablissement_par_formation",
	CAST("1_Effectif_total_candidats_pour_formation" as INT) as "1_effectif_total_candidats_pour_formation",
	CAST("1_1_Dont_effectif_candidates_pour_formation" as INT) as "1_1_dont_effectif_candidates_pour_formation",
	CAST("2_Effectif_total_candidats_phase_principale" as INT) as "2_effectif_total_candidats_phase_principale",
	CAST("2_1_Dont_effectif_candidats_postule_internat" as INT) as "2_1_dont_effectif_candidats_postule_internat",
	CAST("3_Effectif_candidats_neo_bacheliers_generaux_phase_principale" as INT) as "3_effectif_candidats_neo_bacheliers_generaux_phase_principale",
	CAST("3_1_Dont_effectif_candidats_boursiers_neo_bacheliers_generaux_phase_principale" as INT) as "3_1_dont_effectif_candidats_boursiers_neo_bacheliers_generaux_phase_principale",
	CAST("4_Effectif_candidats_neo_bacheliers_technologiques_phase_principale" as INT) as "4_effectif_candidats_neo_bacheliers_technologiques_phase_principale",
	CAST("4_1_Dont_effectif_candidats_boursiers_neo_bacheliers_technologiques_phase_principale" as INT) as "4_1_dont_effectif_candidats_boursiers_neo_bacheliers_technologiques_phase_principale",
	CAST("5_Effectif_candidats_neo_bacheliers_professionnels_phase_principale" as INT) as "5_effectif_candidats_neo_bacheliers_professionnels_phase_principale",
	CAST("5_1_Dont_effectif_candidats_boursiers_neo_bacheliers_professionnels_phase_principale" as INT) as "5_1_dont_effectif_candidats_boursiers_neo_bacheliers_professionnels_phase_principale",
	CAST("6_Effectif_autres_candidats_phase_principale" as INT) as "6_effectif_autres_candidats_phase_principale",
	CAST("7_Effectif_total_candidats_phase_complementaire" as INT) as "7_effectif_total_candidats_phase_complementaire",
	CAST("8_Effectif_candidats_neo_bacheliers_generaux_phase_complementaire" as INT) as "8_effectif_candidats_neo_bacheliers_generaux_phase_complementaire",
	CAST("9_Effectif_candidats_neo_bacheliers_technologique_phase_complementaire" as INT) as "9_effectif_candidats_neo_bacheliers_technologique_phase_complementaire",
	CAST("10_Effectif_candidats_neo_bacheliers_professionnels_phase_complementaire" as INT) as "10_effectif_candidats_neo_bacheliers_professionnels_phase_complementaire",
	CAST("11_Effectifs_autres_candidats_phase_complementaire" as INT) as "11_effectifs_autres_candidats_phase_complementaire",
	CAST("12_Effectif_total_candidats_classes_par_etablissement_phase_principale" as INT) as "12_effectif_total_candidats_classes_par_etablissement_phase_principale",
	CAST("13_Effectif_candidats_classes_par_etablissement_phase_complementaire" as INT) as "13_effectif_candidats_classes_par_etablissement_phase_complementaire",
	CAST("14_Effectif_candidats_classes_par_etablissement_internat_CPGE" as INT) as "14_effectif_candidats_classes_par_etablissement_internat_cpge",
	CAST("15_Effectif_candidats_classes_par_etablissement_hors_internat_CPGE" as INT) as "15_effectif_candidats_classes_par_etablissement_hors_internat_cpge",
	CAST("16_Effectif_candidats_neo_bacheliers_generaux_classes_par_etablissement" as INT) as "16_effectif_candidats_neo_bacheliers_generaux_classes_par_etablissement",
	CAST("16_1_Dont_effectif_candidats_boursiers_neo_bacheliers_generaux_classes_par_etablissement" as INT) as "16_1_dont_effectif_candidats_boursiers_neo_bacheliers_generaux_classes_par_etablissement",
	CAST("17_Effectif_candidats_neo_bacheliers_technologiques_classes_par_etablissement" as INT) as "17_effectif_candidats_neo_bacheliers_technologiques_classes_par_etablissement",
	CAST("17_1_Dont_effectif_candidats_boursiers_neo_bacheliers_technologiques_classes_par_etablissement" as INT) as "17_1_dont_effectif_candidats_boursiers_neo_bacheliers_technologiques_classes_par_etablissement",
	CAST("18_Effectif_candidats_neo_bacheliers_professionnels_classes_par_etablissement" as INT) as "18_effectif_candidats_neo_bacheliers_professionnels_classes_par_etablissement",
	CAST("18_1_Dont_effectif_candidats_boursiers_neo_bacheliers_professionnels_classes_par_etablissement" as INT) as "18_1_dont_effectif_candidats_boursiers_neo_bacheliers_professionnels_classes_par_etablissement",
	CAST("19_Effectif_autres_candidats_classes_par_etablissement" as INT) as "19_effectif_autres_candidats_classes_par_etablissement",
	CAST("20_Effectif_total_candidats_recu_proposition_admission_part_etablissement" as INT) as "20_effectif_total_candidats_recu_proposition_admission_part_etablissement",
	CAST("21_Effectif_total_candidats_accepte_proposition_etablissement_admis" as INT) as "21_effectif_total_candidats_accepte_proposition_etablissement_admis",
	CAST("21_1_Dont_effectif_candidates_admises" as INT) as "21_1_dont_effectif_candidates_admises",
	CAST("22_Effectif_admis_phase_principale" as INT) as "22_effectif_admis_phase_principale",
	CAST("23_Effectif_admis_phase_complementaire" as INT) as "23_effectif_admis_phase_complementaire",
	CAST("23_1_Dont_effectif_admis_recu_leur_proposition_admission_a_ouverture_procedure_principale" as INT) as "23_1_dont_effectif_admis_recu_leur_proposition_admission_a_ouverture_procedure_principale",
	CAST("23_2_Dont_effectif_admis_recu_leur_proposition_admission_avant_baccalaureat" as INT) as "23_2_dont_effectif_admis_recu_leur_proposition_admission_avant_baccalaureat",
	CAST("23_3_Dont_effectif_admis_recu_leur_proposition_admission_avant_fin_procedure_principale" as INT) as "23_3_dont_effectif_admis_recu_leur_proposition_admission_avant_fin_procedure_principale",
	CAST("23_4_Dont_effectif_admis_internat" as INT) as "23_4_dont_effectif_admis_internat",
	CAST("23_5_Dont_effectif_admis_boursiers_neo_bacheliers" as INT) as "23_5_dont_effectif_admis_boursiers_neo_bacheliers",
	CAST("24_Effectif_admis_neo_bacheliers" as INT) as "24_effectif_admis_neo_bacheliers",
	CAST("25_Effectif_admis_neo_bacheliers_generaux" as INT) as "25_effectif_admis_neo_bacheliers_generaux",
	CAST("26_Effectif_admis_neo_bacheliers_technologiques" as INT) as "26_effectif_admis_neo_bacheliers_technologiques",
	CAST("27_Effectif_admis_neo_bacheliers_professionnels" as INT) as "27_effectif_admis_neo_bacheliers_professionnels",
	CAST("28_Effectif_autres_candidats_admis" as INT) as "28_effectif_autres_candidats_admis",
	CAST("28_1_Dont_effectif_admis_neo_bacheliers_sans_information_mention" as INT) as "28_1_dont_effectif_admis_neo_bacheliers_sans_information_mention",
	CAST("28_2_Dont_effectif_admis_neo_bacheliers_sans_mention" as INT) as "28_2_dont_effectif_admis_neo_bacheliers_sans_mention",
	CAST("28_3_Dont_effectif_admis_neo_bacheliers_mention_Assez_Bien" as INT) as "28_3_dont_effectif_admis_neo_bacheliers_mention_assez_bien",
	CAST("28_4_Dont_effectif_admis_neo_bacheliers_mention_Bien" as INT) as "28_4_dont_effectif_admis_neo_bacheliers_mention_bien",
	CAST("28_5_Dont_effectif_admis_neo_bacheliers_mention_Tres_Bien" as INT) as "28_5_dont_effectif_admis_neo_bacheliers_mention_tres_bien",
	CAST("28_6_Dont_effectif_admis_neo_bacheliers_mention_Tres_Bien_felicitations" as INT) as "28_6_dont_effectif_admis_neo_bacheliers_mention_tres_bien_felicitations",
	CAST("29_Effectif_admis_neo_bacheliers_generaux_mention" as INT) as "29_effectif_admis_neo_bacheliers_generaux_mention",
	CAST("30_Effectif_admis_neo_bacheliers_technologiques_mention" as INT) as "30_effectif_admis_neo_bacheliers_technologiques_mention",
	CAST("31_Effectif_admis_neo_bacheliers_professionnels_mention" as INT) as "31_effectif_admis_neo_bacheliers_professionnels_mention",
	CAST("31_1_Dont_effectif_admis_issus_meme_etablissement_BTS_CPGE" as INT) as "31_1_dont_effectif_admis_issus_meme_etablissement_bts_cpge",
	CAST("31_2_Dont_effectif_admises_issues_meme_etablissement_BTS_CPGE" as INT) as "31_2_dont_effectif_admises_issues_meme_etablissement_bts_cpge",
	CAST("31_3_Dont_effectif_admis_issus_meme_academie" as INT) as "31_3_dont_effectif_admis_issus_meme_academie",
	CAST("31_4_Dont_effectif_admis_issus_meme_academie_Paris_Creteil_Versailles_reunies" as INT) as "31_4_dont_effectif_admis_issus_meme_academie_paris_creteil_versailles_reunies",
	CAST("pourcentage_admis_recu_leur_proposition_admission_a_ouverture_procedure_principale" as INT) as "Pourcentage_admis_recu_leur_proposition_admission_a_ouverture_procedure_principale",
	CAST("pourcentage_admis_recu_leur_proposition_admission_avant_baccalaureat" as INT) as "Pourcentage_admis_recu_leur_proposition_admission_avant_baccalaureat",
	CAST("pourcentage_admis_recu_leur_proposition_admission_avant_fin_procedure_principale" as INT) as "Pourcentage_admis_recu_leur_proposition_admission_avant_fin_procedure_principale",
	CAST("pourcentage_admis_dont_filles" as INT) as "Pourcentage_admis_dont_filles",
	CAST("pourcentage_admis_neo_bacheliers_issus_meme_academie" as INT) as "Pourcentage_admis_neo_bacheliers_issus_meme_academie",
	CAST("pourcentage_admis_neo_bacheliers_issus_meme_academie_Paris_Creteil_Versailles_reunies" as INT) as "Pourcentage_admis_neo_bacheliers_issus_meme_academie_paris_creteil_versailles_reunies",
	CAST("pourcentage_admis_neo_bacheliers_issus_meme_etablissement_BTS_CPGE" as INT) as "Pourcentage_admis_neo_bacheliers_issus_meme_etablissement_bts_cpge",
	CAST("pourcentage_admis_neo_bacheliers_boursiers" as INT) as "Pourcentage_admis_neo_bacheliers_boursiers",
	CAST("pourcentage_admis_neo_bacheliers" as INT) as "Pourcentage_admis_neo_bacheliers",
	CAST("pourcentage_admis_neo_bacheliers_sans_information_mention" as INT) as "Pourcentage_admis_neo_bacheliers_sans_information_mention",
	CAST("pourcentage_admis_neo_bacheliers_sans_mention" as INT) as "Pourcentage_admis_neo_bacheliers_sans_mention",
	CAST("pourcentage_admis_neo_bacheliers_mention_Assez_Bien" as INT) as "Pourcentage_admis_neo_bacheliers_mention_assez_bien",
	CAST("pourcentage_admis_neo_bacheliers_mention_Bien" as INT) as "Pourcentage_admis_neo_bacheliers_mention_bien",
	CAST("pourcentage_admis_neo_bacheliers_mention_Tres_Bien" as INT) as "Pourcentage_admis_neo_bacheliers_mention_tres_bien",
	CAST("pourcentage_admis_neo_bacheliers_mention_Tres_Bien_felicitations" as INT) as "Pourcentage_admis_neo_bacheliers_mention_tres_bien_felicitations",
	CAST("pourcentage_admis_neo_bacheliers_generaux" as INT) as "Pourcentage_admis_neo_bacheliers_generaux",
	CAST("31_5_Dont_pourcentage_admis_mention_BG" as INT) as "31_5_dont_pourcentage_admis_mention_bg",
	CAST("pourcentage_admis_neo_bacheliers_technologiques" as INT) as "Pourcentage_admis_neo_bacheliers_technologiques",
	CAST("31_6_Dont_pourcentage_admis_mention_BT" as INT) as "31_6_dont_pourcentage_admis_mention_bt",
	CAST("pourcentage_admis_neo_bacheliers_professionnels" as INT) as "Pourcentage_admis_neo_bacheliers_professionnels",
	CAST("31_7_Dont_pourcentage_admis_mention_BP" as INT) as "31_7_dont_pourcentage_admis_mention_bp",
	CAST("32_Effectif_candidats_terminale_generale_recu_proposition_admission_part_etablissement" as INT) as "32_effectif_candidats_terminale_generale_recu_proposition_admission_part_etablissement",
	CAST("32_1_Dont_effectif_candidats_boursiers_terminale_generale_recu_proposition_admission_part_etablissement" as INT) as "32_1_dont_effectif_candidats_boursiers_terminale_generale_recu_proposition_admission_part_etablissement",
	CAST("33_Effectif_candidats_terminale_technologique_recu_proposition_admission_part_etablissement" as INT) as "33_effectif_candidats_terminale_technologique_recu_proposition_admission_part_etablissement",
	CAST("33_1_Dont_effectif_candidats_boursiers_terminale_technologique_recu_proposition_admission_part_etablissement" as INT) as "33_1_dont_effectif_candidats_boursiers_terminale_technologique_recu_proposition_admission_part_etablissement",
	CAST("34_Effectif_candidats_terminale_professionnelle_recu_proposition_admission_part_etablissement" as INT) as "34_effectif_candidats_terminale_professionnelle_recu_proposition_admission_part_etablissement",
	CAST("34_1_Dont_effectif_candidats_boursiers_terminale_generale_professionnelle_recu_proposition_admission_part_etablissement" as INT) as "34_1_dont_effectif_candidats_boursiers_terminale_generale_professionnelle_recu_proposition_admission_part_etablissement",
	CAST("35_Effectif_autres_candidats_recu_proposition_admission_part_etablissement" as INT) as "35_effectif_autres_candidats_recu_proposition_admission_part_etablissement",
	TRIM("Regroupement_1_effectue_par_formations_pour_classements") as "Regroupement_1_effectue_par_formations_pour_classements",
	CAST("Rang_dernier_appele_groupe_1" as INT) as "Rang_dernier_appele_groupe_1",
	TRIM("Regroupement_2_effectue_par_formations_pour_classements") as "Regroupement_2_effectue_par_formations_pour_classements",
	CAST("Rang_dernier_appele_groupe_2" as INT) as "Rang_dernier_appele_groupe_2",
	TRIM("Regroupement_3_effectue_par_formations_pour_classements") as "Regroupement_3_effectue_par_formations_pour_classements",
	CAST("Rang_dernier_appele_groupe_3" as INT) as "Rang_dernier_appele_groupe_3",
	TRIM("list_com") as "List_com",
	TRIM("tri") as "Tri",
	CAST("cod_aff_form" as INT) as "Cod_aff_form",
	TRIM("Concours_communs_et_banque_epreuves") as "Concours_communs_et_banque_epreuves",
	TRIM("Lien_formation_plateforme_Parcoursup") as "Lien_formation_plateforme_parcoursup",
	CAST("Taux_dacces" as INT) as "Taux_dacces",
	CAST("Part_terminales_generales_qui_etaient_position_recevoir_proposition_phase_principale" as INT) as "Part_terminales_generales_qui_etaient_position_recevoir_proposition_phase_principale",
	CAST("Part_terminales_technologiques_qui_etaient_position_recevoir_proposition_phase_principale" as INT) as "Part_terminales_technologiques_qui_etaient_position_recevoir_proposition_phase_principale",
	CAST("Part_terminales_professionnelles_qui_etaient_position_recevoir_proposition_phase_principale" as INT) as "Part_terminales_professionnelles_qui_etaient_position_recevoir_proposition_phase_principale",
	TRIM("etablissement_id_paysage") as "Etablissement_id_paysage",
	TRIM("composante_id_paysage") as "Composante_id_paysage"
FROM
    "Test".parcoursup2024
);


COMMIT;
